matrix:
  include:
    - language: node_js
      node_js:
        - "node"
      before_install:
        - "cd frontend"
        - "npm install -g @angular/cli"
      before_script:
        - "yarn install"
        - "gradle build"
      script:
        - "gradle test"
      cache: yarn
    - language: java
      jdk:
        - oraclejdk8
      before_install:
          - chmod +x gradlew
      before_cache:
        - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
        - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
      cache:
        directories:
          - $HOME/.gradle/caches/
          - $HOME/.gradle/wrapper/
      before_script:
        - "cd backend"
        - "gradle clean"
      script:
        - "gradle test"
branches:
  except:
    - gh-pages