version: '3'
services:
  backend:
    build: ./backend/build
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql/sensum?autoReconnect=true&useSSL=false
      MYSQL_USERNAME: ${MYSQL_USERNAME}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      - main
  frontend:
    build: ./frontend/build
    ports:
      - "80:80"
    networks:
      - main
  db:
    image: mysql:5.7
    environment:
      MYSQL_USER: ${MYSQL_USERNAME}
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: tutors
    ports:
      - "3306:3306"
    networks:
      - main
networks:
  main:

